name: flutter_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  get: ^4.3.8
  http: ^0.13.5
  dio: ^4.0.0
  flutter_bloc: ^8.1.1
  flutter_offline: ^2.1.0
  shared_preferences: ^2.0.5
  internet_connection_checker: ^0.0.1+3
  lottie: ^1.3.0
  country_code_picker: ^2.0.2
  pinput: ^2.2.11
  intl: ^0.17.0
  flutter_svg: ^1.1.4
  carousel_slider: ^4.1.1
  restart_app: ^1.1.0
  easy_localization: ^3.0.1
  flutter_phoenix: ^1.1.0






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/lang/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 700
         - asset: assets/fonts/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/Poppins-Regular.ttf
           weight: 400
         - asset: assets/fonts/Poppins-Light.ttf
           weight: 300




  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
